name: E2E
on:
    push:
        branches:
            - "**"
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                    version: 8
            - uses: actions/setup-node@v4
              with:
                    node-version: 20
                    cache: 'pnpm'
            - run: pnpm install
            - run: pnpm exec playwright install
            - run: pnpm run build
            - run: pnpm e2e
            - uses: actions/upload-artifact@v4
              if: always()
              with:
                    name: playwright-report
                    path: playwright-report/
                    retention-days: 30
