name: E2E
on:
    push:
        branches:
            - "**"
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                    version: 9
            - uses: actions/setup-node@v4
              with:
                    node-version: 20
                    cache: 'pnpm'
            - run: pnpm --filter !internal --filter !site install --frozen-lockfile
            - run: pnpm exec playwright install --with-deps
            - run: pnpm run build
            - run: pnpm e2e
