name: Generate Page Cache
on:
  workflow_dispatch:
    inputs:
      locale:
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: "pnpm"
        - run: pnpm install
        - run: pnpm exec tsx scripts/generate-page-cache.ts
          env:
            FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
            FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
            LOCALE: ${{ github.event.inputs.locale }}
