name: Generate Page Cache
on:
  workflow_dispatch:
    inputs:
      locale:
        required: true

jobs:
  generate:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
              version: 8
        - uses: actions/setup-node@v3
          with:
              node-version: 18.17.0
        - run: pnpm install
        - run: echo "LOCALE=${{ github.event.inputs.locale }}" >> $GITHUB_ENV
        - run: pnpm ts-node scripts/generate-page-cache.ts
            